server:
  port: 8081

#druid
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wendao?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # ?????
    initialSize: 5
    # ???????
    minIdle: 10
    # ???????
    maxActive: 20
    # ?????????????
    maxWait: 60000
    # ???????????????????????????????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????????
    minEvictableIdleTimeMillis: 300000
    # ??????????????????????
    maxEvictableIdleTimeMillis: 900000
    # ??????????
    validationQuery: SELECT 1 FROM DUAL
    #??????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
    testWhileIdle: true
    #??????????????????????true??????false????????????????
    testOnBorrow: false
    #??????????????????????true??????false????????????????
    testOnReturn: false
    #??PsCache??????????PSCache???
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #   ?????????filters????????sql?????'wall'?????
    filters: stat,wall,log4j
    #????DruidDatasource?????
    useGlobalDataSourceStat: true
    #??connectProperties?????mergesql????sQL??
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;
  #redis
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 1000
        max-idle: 800
        min-idle: 500
        max-wait: 500
  elasticsearch:
    rest:
      uris: localhost:9300

logging:
  level:
    root: info
    com.example.wendao.dao: debug

#oauth2 ??qq?github

#???